- name: Copy SSH public key to remote servers
  hosts: all
  become: false
  tasks:
    - name: Ensure the .ssh directory exists on the remote server
      file:
        path: ~/.ssh
        state: directory
        mode: "0700"
    - name: Copy SSH public key to the remote server
      ansible.builtin.copy:
        src: ~/.ssh/id_ed25519.pub
        dest: ~/.ssh/authorized_keys
        owner: "{{ ansible_user }}"
        mode: "0600"
      remote_src: no
    - name: Ensure correct permissions on the authorized_keys file
      file:
        path: ~/.ssh/authorized_keys
        mode: "0600"
